POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Admin User",
  "email": "admin2@example.com",
  "password": "password123",
  "role": "admin"
}


POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Staff User",
  "email": "staff@example.com",
  "password": "123456",
  "role": "staff"
}
